FROM python:3.12-slim


RUN pip install --upgrade pip

WORKDIR /django_app
COPY /cat_breeder /django_app/
COPY requirements.txt /django_app/

RUN pip install -r requirements.txt

CMD python manage.py migrate \
    && python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='root').exists() or User.objects.create_superuser('root', 'root')" \
    && python manage.py collectstatic --no-input \
    && gunicorn cat_breeder.wsgi:application --bind 0.0.0.0:8000