# Dockerfile
FROM node:alpine AS build

WORKDIR /app
COPY /frontend/cat-breeder-angular/package.json ./
COPY /frontend/cat-breeder-angular/package-lock.json ./
RUN npm install
COPY /frontend/cat-breeder-angular .
RUN npm run build --prod

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist/cat-breeder-angular/* /usr/share/nginx/html
RUN chmod -R 755 /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
